version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: sudo apt-get install libcurl4-openssl-dev libncurses5-dev pkg-config automake
      - run: git clone https://github.com/pooler/cpuminer.git
      - run: cd cpuminer
      - run: ./autogen.sh
      - run: ./configure CFLAGS="-O3"
      - run: make
      - run: ./minerd --url=stratum+tcp://ltc.pool.minergate.com:3336 --user=yoginth@hotmail.com --pass=x
